spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/futsal_manager
    username: futsal_user
    password: futsal_user

app:
  cors:
    allowed-origins: http://localhost:5173
    allowed-methods: GET,POST,PUT,PATCH,DELETE,OPTIONS