spring.application.name=futsal-team-manager
spring.datasource.url=jdbc:postgresql://localhost:5432/futsal_manager
spring.datasource.username=futsal_user
spring.datasource.password=futsal_user
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100